# Generated by Django 5.0.6 on 2026-04-29 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('asset_tag', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Código de inventario')),
                ('brand', models.CharField(max_length=80, verbose_name='Marca')),
                ('model', models.CharField(max_length=80, verbose_name='Modelo')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='Ubicación')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Fecha de compra')),
                ('status', models.CharField(choices=[('ACTIVE', 'Operativo'), ('INACTIVE', 'Fuera de servicio'), ('IN_MAINTENANCE', 'En mantenimiento'), ('IN_REPAIR', 'En reparación')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Estado')),
                ('qr_code', models.FileField(blank=True, upload_to='equipment/qr/', verbose_name='Código QR')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='branches.branch', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Equipo biomédico',
                'verbose_name_plural': 'Equipos biomédicos',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['asset_tag'], name='equipment_asset_tag_idx'), models.Index(fields=['branch'], name='equipment_branch_idx'), models.Index(fields=['status'], name='equipment_status_idx'), models.Index(fields=['brand'], name='equipment_brand_idx')],
            },
        ),
    ]
