# Generated by Django 5.0.6 on 2026-05-05 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('catalog', '0001_initial'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='equipment',
            name='equipment_brand_idx',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='model',
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='catalog.equipmentmodel', verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='risk_class',
            field=models.CharField(blank=True, choices=[('I', 'Clase I — riesgo bajo'), ('IIA', 'Clase IIA — riesgo moderado'), ('IIB', 'Clase IIB — riesgo moderado-alto'), ('III', 'Clase III — riesgo alto')], db_index=True, max_length=4, null=True, verbose_name='Clasificación de riesgo INVIMA'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['equipment_model'], name='equipment_model_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['risk_class'], name='equipment_risk_class_idx'),
        ),
    ]
