# Generated by Django 5.0.6 on 2026-05-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_model_and_risk_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='mtbf_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tiempo promedio entre fallas consecutivas. Recalculado automáticamente.', max_digits=10, null=True, verbose_name='MTBF (horas)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='mttr_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tiempo promedio para resolver una falla. Recalculado automáticamente.', max_digits=10, null=True, verbose_name='MTTR (horas)'),
        ),
    ]
