# Generated by Django 5.0.6 on 2026-05-16 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_assigned_engineer_assigned_technician'),
        ('scheduling', '0002_assigned_engineer_assigned_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='scheduled_maintenance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_record', to='scheduling.maintenanceschedule', verbose_name='Agendamiento cumplido'),
        ),
    ]
