# Generated by Django 5.0.6 on 2026-05-01 14:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Reportada el')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('severity', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], db_index=True, max_length=10, verbose_name='Severidad')),
                ('resolved', models.BooleanField(db_index=True, default=False, verbose_name='Resuelta')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resuelta el')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notas de resolución')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='failures', to='equipment.equipment', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Reporte de falla',
                'verbose_name_plural': 'Reportes de falla',
                'ordering': ['-reported_at'],
                'indexes': [models.Index(fields=['equipment', '-reported_at'], name='fail_eq_reported_idx'), models.Index(fields=['severity'], name='fail_severity_idx'), models.Index(fields=['resolved'], name='fail_resolved_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='failurerecord',
            constraint=models.CheckConstraint(check=models.Q(('resolved', False), ('resolved_at__isnull', False), _connector='OR'), name='failure_resolved_consistency'),
        ),
    ]
