# Generated by Django 5.0.6 on 2026-05-05 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Nombre comercial único de la marca.', max_length=120, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='brand_name_idx'), models.Index(fields=['is_active'], name='brand_is_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='Modelo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_models', to='catalog.brand', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Modelo de equipo',
                'verbose_name_plural': 'Modelos de equipo',
                'ordering': ['brand__name', 'name'],
                'indexes': [models.Index(fields=['brand'], name='eqmodel_brand_idx'), models.Index(fields=['name'], name='eqmodel_name_idx'), models.Index(fields=['is_active'], name='eqmodel_is_active_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='equipmentmodel',
            constraint=models.UniqueConstraint(fields=('brand', 'name'), name='equipment_model_unique_per_brand'),
        ),
    ]
