name: Backend Deploy CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: backend
        run: pip install -r requirements.txt

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        env:
            DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            DJANGO_EMAIL_HOST_PASSWORD: ${{ secrets.DJANGO_EMAIL_HOST_PASSWORD }}
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}

          script: |

            cd ~/backend_biomedico/backend

            echo "Reset repository"
            git fetch origin
            git reset --hard origin/main
            git clean -fd

            echo "Clean docker cache"
            docker system prune -f

            echo "Pull latest images"
            docker-compose pull

            echo "Build containers"
            docker-compose build

            echo "Run containers"
            docker-compose up -d

            echo "Run migrations"
            docker-compose exec backend python manage.py migrate

            echo "Collect static"
            docker-compose exec backend python manage.py collectstatic --noinput
